//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospedajes
    {
        public string codigoInterno { get; set; }
        public string nombre { get; set; }
        public string calle { get; set; }
        public string localidad { get; set; }
        public double precioH { get; set; }
        public string tipoH { get; set; }
        public bool activoH { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
