//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incluyen
    {
        public string codigoH { get; set; }
        public int codigoPV { get; set; }
        public int cantNoches { get; set; }
    
        public virtual Hospedajes Hospedajes { get; set; }
    }
}
