//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetesViajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaquetesViajes()
        {
            this.Incluyen = new HashSet<Incluyen>();
        }
    
        public int codigo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public int cantidadDiasP { get; set; }
        public double precioIndividual { get; set; }
        public double precioDosP { get; set; }
        public double precioTresP { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incluyen> Incluyen { get; set; }
        public virtual Vuelos VuelosI { get; set; }
        public virtual Vuelos VuelosV { get; set; }
    }
}
