//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public string codigo { get; set; }
        public System.DateTime fechaHoraP { get; set; }
        public System.DateTime fechaHoraL { get; set; }
        public double precioV { get; set; }
        public bool activoV { get; set; }
    
        public virtual Estados EstadosA { get; set; }
        public virtual Estados EstadosP { get; set; }
    }
}
